init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "13.5"

# Install scripts. (runs after repo cloning)
install:
  - ps: |
      if ($env:NPM_TOKEN.length -eq 0) {
        Write-Host "This job originated from an untrusted source.";
        if (Test-Path ./.npmrc) {
          Write-Host "Renaming .npmrc to disable it";
          Rename-Item -Path ./.npmrc -NewName "npmrcdisabled";
        }
      }
  - ps: Install-Product node $env:nodejs_version
  - npm install --ignore-scripts

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

build: off

deploy_script:
  - if %APPVEYOR_REPO_TAG% EQU true npm config set '//registry.npmjs.org/:_authToken' "%NPM_TOKEN%" && npm publish .
